# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 724)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.video_lbl = QtWidgets.QLabel(self.centralwidget)
        self.video_lbl.setGeometry(QtCore.QRect(30, 80, 601, 441))
        self.video_lbl.setAutoFillBackground(False)
        self.video_lbl.setStyleSheet("background-color: rgb(98, 255, 0);\n"
"\n"
"")
        self.video_lbl.setText("")
        self.video_lbl.setPixmap(QtGui.QPixmap(":/newPrefix/images/BG.jpg"))
        self.video_lbl.setScaledContents(True)
        self.video_lbl.setObjectName("video_lbl")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 110, 821, 671))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("border-radius:30px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: transparent;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pauseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pauseBtn.setGeometry(QtCore.QRect(320, 640, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pauseBtn.setFont(font)
        self.pauseBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/videoStop.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/E:/Mohammed/self learning/MSH_GitHub/Embedded systems/GUI_Interfaces_ES/Pyt5/lift/images/on.jpg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.pauseBtn.setIcon(icon)
        self.pauseBtn.setIconSize(QtCore.QSize(32, 32))
        self.pauseBtn.setObjectName("pauseBtn")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(210, 640, 101, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("background-color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/videoStart.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/E:/Mohammed/self learning/MSH_GitHub/Embedded systems/GUI_Interfaces_ES/Pyt5/lift/images/on.jpg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.startBtn.setIcon(icon1)
        self.startBtn.setIconSize(QtCore.QSize(32, 32))
        self.startBtn.setObjectName("startBtn")
        self.productImg = QtWidgets.QLabel(self.centralwidget)
        self.productImg.setGeometry(QtCore.QRect(220, 540, 111, 91))
        self.productImg.setAutoFillBackground(False)
        self.productImg.setStyleSheet("background-image: url(:/newPrefix/images/BG.jpg);\n"
"border:none\n"
"")
        self.productImg.setText("")
        self.productImg.setScaledContents(True)
        self.productImg.setObjectName("productImg")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 550, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 580, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"background-color: transparent;")
        self.label_5.setObjectName("label_5")
        self.typeLbl = QtWidgets.QLabel(self.centralwidget)
        self.typeLbl.setGeometry(QtCore.QRect(410, 550, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.typeLbl.setFont(font)
        self.typeLbl.setStyleSheet("\n"
"background-color: transparent;")
        self.typeLbl.setText("")
        self.typeLbl.setObjectName("typeLbl")
        self.priceLbl = QtWidgets.QLabel(self.centralwidget)
        self.priceLbl.setGeometry(QtCore.QRect(410, 580, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.priceLbl.setFont(font)
        self.priceLbl.setStyleSheet("\n"
"background-color: transparent;")
        self.priceLbl.setText("")
        self.priceLbl.setObjectName("priceLbl")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 641, 691))
        self.label_2.setStyleSheet("border-radius:2px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.durationLbl = QtWidgets.QLabel(self.centralwidget)
        self.durationLbl.setGeometry(QtCore.QRect(430, 640, 131, 31))
        self.durationLbl.setText("")
        self.durationLbl.setObjectName("durationLbl")
        self.label_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 631, 71))
        self.label_3.setStyleSheet("border:none")
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.label.raise_()
        self.video_lbl.raise_()
        self.pauseBtn.raise_()
        self.startBtn.raise_()
        self.productImg.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.typeLbl.raise_()
        self.priceLbl.raise_()
        self.durationLbl.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.startBtn, self.pauseBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Grocery "))
        self.pauseBtn.setText(_translate("MainWindow", "Stop"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "Type:"))
        self.label_5.setText(_translate("MainWindow", "Price:"))
        self.label_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600;\">W</span><span style=\" font-size:36pt;\">elcome </span><span style=\" font-size:36pt; font-weight:600; font-style:italic; color:#34811d;\">to</span><span style=\" font-size:36pt; vertical-align:super;\">  </span><span style=\" font-size:36pt; font-weight:600; color:#781a1a; vertical-align:super;\">Smart Grocery</span></p></body></html>"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
